inherit_from: 
  - '.rubocop/base.yml'
  - '.rubocop/todo.yml'

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'spec/dummy/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 110
  Exclude:
    - 'spec/**/*'

Naming/PredicateName:
  Exclude:
    - 'lib/profiler/active_record.rb'
