defaults: &defaults
  working_directory: ~/profiler
  steps:
    - checkout
    - run:
        name: Which bundler?
        command: bundle -v
    - restore_cache:
        keys:
          - profiler-bundle-v2-{{ .Branch }}-{{ checksum "Gemfile" }}
          - profiler-bundle-v2-{{ checksum "Gemfile" }}
    - run:
        name: Bundle Install
        command: |
          bundle check --path=~/profiler/vendor/bundle || bundle install
    - save_cache:
        key: profiler-bundle-v2-{{ .Branch }}-{{ checksum "Gemfile" }}
        paths:
          - ~/profiler/vendor/bundle
    - run:
        name: Wait for DB
        command: dockerize -wait tcp://localhost:5432 -timeout 1m
    - run:
        name: Run test application generator
        command: bundle exec rake test_app
    - run:
        name: Run rspec tests
        command: bundle exec rspec
    - store_artifacts:
        path: /tmp/test-artifacts
        destination: test-artifacts
    - store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output
    - store_test_results:
        path: /tmp/test-results

version: 2
jobs: 
  ruby-2.3:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.3-node
        environment:
          DB: postgres
          DB_HOST: localhost
          DB_USERNAME: postgres
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: ~/profiler/vendor/bundle
          BUNDLE_GEMFILE: ~/profiler/Gemfile
          COVERAGE_ENABLED: true
          COVERALLS_REPO_TOKEN: rHrAGDxiIZFd9UaAOTdg9Wrn5AH95osNT
          CIRCLE_TEST_REPORTS: /tmp/test-results
          CIRCLE_ARTIFACTS: /tmp/test-artifacts
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: postgres
  ruby-2.4:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          DB: postgres
          DB_HOST: localhost
          DB_USERNAME: postgres
          CIRCLE_TEST_REPORTS: /tmp/test-results
          CIRCLE_ARTIFACTS: /tmp/test-artifacts
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: ~/profiler/vendor/bundle
          BUNDLE_GEMFILE: ~/profiler/Gemfile
          COVERAGE_ENABLED: true
          COVERALLS_REPO_TOKEN: rHrAGDxiIZFd9UaAOTdg9Wrn5AH95osNT
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: postgres
  ruby-2.5:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5-node
        environment:
          DB: postgres
          DB_HOST: localhost
          DB_USERNAME: postgres
          CIRCLE_TEST_REPORTS: /tmp/test-results
          CIRCLE_ARTIFACTS: /tmp/test-artifacts
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: ~/profiler/vendor/bundle
          BUNDLE_GEMFILE: ~/profiler/Gemfile
          COVERAGE_ENABLED: true
          COVERALLS_REPO_TOKEN: rHrAGDxiIZFd9UaAOTdg9Wrn5AH95osNT
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: postgres
workflows:
  version: 2
  build:
    jobs:
      - ruby-2.3
      - ruby-2.4
      - ruby-2.5
